### ISSUE TITLE
Store Generated Certificates in Database

### ISSUE THREAD

**Issue by ATHARVA262005** [ATHARVA262005/GDG-On-Campus-Certificate-Maker#1]
### Description:
 Currently, generated certificates are not being stored in a database. Implement a feature where users can provide their database URI (such as MongoDB or PostgreSQL), and the generated certificates are saved in their database.

### Expected Outcome: 
Once a certificate is generated, it should be automatically stored in the user's specified database.

**Comment by ripu2** [comment]
Not advisavble to store it in DB, will prefer some storage engine, let's connect somewhere to discuss the options

**Comment by VinayGadKerkar** [comment]
can you assign this to me?
