### ISSUE TITLE
Generate Verification URL with Unique Certificate ID

### ISSUE THREAD

**Issue by ATHARVA262005** [ATHARVA262005/GDG-On-Campus-Certificate-Maker#2]
### Description: 
There is no way to generate a verification URL for certificates. Add functionality that generates a unique Certificate ID with each certificate, and provide a URL where users can verify the authenticity of the certificate.

### Expected Outcome:
A unique ID is generated and appended to a verification URL. Users can visit this URL to verify the certificate's authenticity.

**Comment by ripu2** [comment]
Can we connect somewhere, will need a little more context here
