### ISSUE TITLE
Add Live Preview of Certificate

### ISSUE THREAD

**Issue by ATHARVA262005** [ATHARVA262005/GDG-On-Campus-Certificate-Maker#3]
### Description: 
Currently, there is no option for users to preview certificates before downloading or generating them. Implement a live preview feature where users can see how the certificate will look in real-time as they enter their details (e.g., name, course, date).

### Expected Outcome: 
As users input their details, the certificate design should update live, allowing them to make adjustments before finalizing the generation.

**Comment by ripu2** [comment]
Please provide the design that needs to be shown

**Comment by ATHARVA262005** [comment]
> Please provide the design that needs to be shown

Thanks for your interest! Currently, we have a CertificatePreview.jsx component inside the components folder, which handles the certificate preview. It’s already functional and uses a base64 background and other dynamic elements, but it only updates when the user clicks on "Generate Certificate."

Right now, this is only implemented in the bulk certificate generator, and we need to add the live preview functionality for the single certificate generator as well. We want the preview to update in real-time as users input their details, without having to click the generate button.

If you’re familiar with implementing live updates, your contribution would be really appreciated! 😊

![image_2024-10-02_003024291](https://github.com/user-attachments/assets/096d8616-0eca-4481-a7e4-990931c23d96)

**Comment by ripu2** [comment]
Can we connect somewhere, maybe discord or something?

**Comment by ShivamP0077** [comment]
@ATHARVA262005 i want to work on this

**Comment by ATHARVA262005** [comment]
> @ATHARVA262005 i want to work on this

@ShivamP0077 Thanks for your interest in this issue. However, it has been resolved.
